// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cd7y_aPU2zYlOhrGCQ7aCfjr55L5mmQ',
    appId: '1:777949064340:web:06206efa67ee6d609a1881',
    messagingSenderId: '777949064340',
    projectId: 'man-shift-app',
    authDomain: 'man-shift-app.firebaseapp.com',
    storageBucket: 'man-shift-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDviseBYz4qI3l0QYFpfNG04UlJSNWtj30',
    appId: '1:777949064340:ios:13647ccb208a3c9e9a1881',
    messagingSenderId: '777949064340',
    projectId: 'man-shift-app',
    storageBucket: 'man-shift-app.firebasestorage.app',
    iosBundleId: 'com.example.manShift',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgYFoSdhFuVZPH12ntHVfEjOtUGhT6tE',
    appId: '1:777949064340:android:a8e650f847897af69a1881',
    messagingSenderId: '777949064340',
    projectId: 'man-shift-app',
    storageBucket: 'man-shift-app.firebasestorage.app',
  );

}